name: "Mark stale issues and PRs"

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity.'
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity.'
          close-issue-message: 'This issue has been automatically closed due to inactivity.'
          close-pr-message: 'This PR has been automatically closed due to inactivity.'
          days-before-stale: 30  # Days of inactivity before marking as stale
          days-before-close: 7  # Days of inactivity before closing stale issues/PRs
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'do not close'
          exempt-pr-labels: 'do not close'
          remove-stale-when-updated: true
